redis_host = "localhost"
redis_port = 6379
redis_password = ""
rules_min_val = 0
rules_max_val = 999

SET_RULES_DONE_ARREAR_TRADES_OF_LAST_3_MONTHS = 'set_rules_done_arrear_trades_of_last_3_months'
SET_RULES_DONE_ARREAR_TRADES_BETWEEN_LAST_3_TO_12_MONTHS = 'set_rules_done_arrear_trades_between_last_3_to_12_months'
SET_RULES_DONE_PAST_DUE_TRADES_OF_LAST_3_MONTHS = 'set_rules_done_past_due_trades_of_last_3_months'
SET_RULES_DONE_PAST_DUE_TRADES_BETWEEN_LAST_3_TO_12_MONTHS = 'set_rules_done_past_due_trades_between_last_3_to_12_months'
SET_RULES_DONE_TIMELY_TRADES_OF_LAST_3_MONTHS = 'set_rules_done_timely_trades_of_last_3_months'
SET_RULES_DONE_TIMELY_TRADES_BETWEEN_LAST_3_TO_12_MONTHS = 'set_rules_done_timely_trades_between_last_3_to_12_months'
SET_RULES_DONE_TRADES_AVERAGE_DELAY_DAYS = 'set_rules_trades_done_average_delay_days'
SET_RULES_DONE_TRADES_AVERAGE_TOTAL_AMOUNT = 'set_rules_done_trades_total_amount'
